apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  RAILS_ENV: "{{ .Values.cabinsEnvironment }}"
  SMTP_ADDRESS: "{{ .Values.cabinsSMTPHost }}"
  SMTP_PORT: "{{ .Values.cabinsSMTPPort }}"
  SMTP_DOMAIN: "{{ .Values.cabinsSMTPDomain }}"
  DB_SEED: "{{ .Values.cabinsDBSeed }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  RAILS_MASTER_KEY: "{{ .Values.cabinsSecretToken  }}"
  SMTP_USERNAME: "{{ .Values.cabinsSMTPlUser }}"
  SMTP_PASSWORD: "{{ .Values.cabinsSMTPPassword }}"
