apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  RAILS_ENV: "{{ .Values.cabinsEnvironment }}"
  SMTP_ADDRESS: "{{ .Values.cabinsSMTPHost }}"
  SMTP_PORT: "{{ .Values.cabinsSMTPPort }}"
  SMTP_DOMAIN: "{{ .Values.cabinsSMTPDomain }}"
  DB_SEED: "{{ .Values.cabinsDBSeed }}"
  CABINS_HOST: "{{ .Values.cabinsHost }}"
  ACTION_MAILER_DEFAULT_FROM: "{{ .Values.cabinsEmailAddress }}"
  ACTION_MAILER_DEFAULT_TO: "{{ .Values.cabinsEmailAddress }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  SECRET_KEY_BASE: "{{ .Values.cabinsSecretToken }}"
  RAILS_SERVE_STATIC_FILES: "{{ .Values.cabinsServeStaticFiles }}"
  SMTP_USERNAME: "{{ .Values.cabinsSMTPUser }}"
  SMTP_PASSWORD: "{{ .Values.cabinsSMTPPassword }}"
