version: '3.8'
services:
  db:
    image: mariadb:10.7.3
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cabins
    ports:
      - "3000:3000"
    environment:
      CABINS_DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
volumes:
  mariadb:
