image:
  repository: cabins
  pullPolicy: Never
  tag: "latest"

cabinsEnvironment: "development"
cabinsSecretToken: "70f1368ac145410d9e6771e645e7183a"
cabinsSMTPHost: ""
cabinsSMTPPort: ""
cabinsSMTPUser: ""
cabinsSMTPPassword: ""
cabinsDBSeed: ""

mariadb:
  auth:
    database: cabins
    username: cabinsuser
    password: "test"
    rootPassword: "test"
