default:
  plugins:
    - image
    - link
    - textcolor
  toolbar: styleselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify bullist numlist outdent indent | link image | code | codesample

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic forecolor backcolor | undo redo | table
  plugins:
    - table